version: '3.8'

services:
  hlds-panel:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hlds_panel
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/hlds/servers:/hlds_data
      - ./data:/app/data
    environment:
      - PORT=1337
      - NODE_ENV=production